In [ ]:
import requests

url = "https://api.coingecko.com/api/v3/coins/markets"

response = requests.get(url)

print(response.status_code)

data = response.json()

422

In [ ]:
sample ={
    "name":"Rahul",
    "age":20,
    "marks" : [10,20,30]
}

sample["name"]

'Rahul'

In [ ]:
import pandas as pd

df = pd.DataFrame(sample)

df.head()

df.tail()

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

        age  marks
count   3.0    3.0
mean   20.0   20.0
std     0.0   10.0
min    20.0   10.0
25%    20.0   15.0
50%    20.0   20.0
75%    20.0   25.0
max    20.0   30.0

In [ ]:
df[['age','marks']]

   age  marks
0   20     10
1   20     20
2   20     30

In [ ]:
df[df['marks']>20]

    name  age  marks
2  Rahul   20     30

In [ ]:
df["normalize_score"] = df['marks']*1.15

In [ ]:
df

    name  age  marks  normalize_score
0  Rahul   20     10             11.5
1  Rahul   20     20             23.0
2  Rahul   20     30             34.5

In [ ]:
df.isnull().sum()

name               0
age                0
marks              0
normalize_score    0
dtype: int64

In [ ]:
df.rename(columns={'age':'AGE'})

    name  AGE  marks  normalize_score
0  Rahul   20     10             11.5
1  Rahul   20     20             23.0
2  Rahul   20     30             34.5

In [ ]:
df["marks"] = df["marks"].astype(float)
df

    name  age  marks  normalize_score
0  Rahul   20   10.0             11.5
1  Rahul   20   20.0             23.0
2  Rahul   20   30.0             34.5

In [ ]:
df.nlargest(5,"normalize_score")

    name  age  marks  normalize_score
2  Rahul   20   30.0             34.5
1  Rahul   20   20.0             23.0
0  Rahul   20   10.0             11.5

In [ ]:
import requests
import pandas as pd
import numpy as np
from datetime import datetime, timedelta


url = "https://api.coingecko.com/api/v3/coins/markets"


params = {
    "vs_currency": "inr",           # Prices in Indian Rupees
    "order": "market_cap_desc",     # Sort by market cap (largest first)
    "per_page": 50,                 # Get top 50 cryptocurrencies
    "page": 1,                      # First page of results
    "sparkline": "false"            # Don't include sparkline (keeps it simple)

}

response = requests.get(url, params = params)


print(f"\nResponse Status Code: {response.status_code}")

if response.status_code == 200:
    print("✅ API call successful!")
else:
    print(f"❌ API call failed with status code: {response.status_code}")
    print("Please wait a minute and try again (rate limiting)")

Response Status Code: 200
✅ API call successful!

In [ ]:
raw_data = response.json()

for key, value in raw_data[0].items():
  print(f"  {key} : {value}")

  id : bitcoin
  symbol : btc
  name : Bitcoin
  image : https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400
  current_price : 7632111
  market_cap : 152799382297656
  market_cap_rank : 1
  fully_diluted_valuation : 152799382297656
  total_volume : 1682722173466
  high_24h : 7650670
  low_24h : 7578108
  price_change_24h : 49533
  price_change_percentage_24h : 0.65325
  market_cap_change_24h : 886028393129
  market_cap_change_percentage_24h : 0.58325
  circulating_supply : 20027378.0
  total_supply : 20027378.0
  max_supply : 21000000.0
  ath : 11187013
  ath_change_percentage : -31.77704
  ath_date : 2025-10-06T18:57:42.558Z
  atl : 3993.42
  atl_change_percentage : 191017.20554
  atl_date : 2013-07-05T00:00:00.000Z
  roi : None
  last_updated : 2026-05-10T12:14:11.914Z

In [ ]:
df_raw = pd.DataFrame(raw_data)
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                50 non-null     object
 1   symbol                            50 non-null     object
 2   name                              50 non-null     object
 3   image                             50 non-null     object
 4   current_price                     50 non-null     float64
 5   market_cap                        50 non-null     int64
 6   market_cap_rank                   50 non-null     int64
 7   fully_diluted_valuation           50 non-null     int64
 8   total_volume                      49 non-null     float64
 9   high_24h                          49 non-null     float64
 10  low_24h                           49 non-null     float64
 11  price_change_24h                  49 non-null     float64
 12  price_change_percentage_24h       49 non-null     float64
 13  market_cap_change_24h             49 non-null     float64
 14  market_cap_change_percentage_24h  49 non-null     float64
 15  circulating_supply                50 non-null     float64
 16  total_supply                      50 non-null     float64
 17  max_supply                        25 non-null     float64
 18  ath                               50 non-null     float64
 19  ath_change_percentage             50 non-null     float64
 20  ath_date                          50 non-null     object
 21  atl                               50 non-null     float64
 22  atl_change_percentage             50 non-null     float64
 23  atl_date                          50 non-null     object
 24  roi                               2 non-null      object
 25  last_updated                      50 non-null     object
dtypes: float64(15), int64(3), object(8)
memory usage: 10.3+ KB

In [ ]:
columns_to_keep = [
    'id',
    'symbol',
    'name',
    'current_price',
    'market_cap',
    'total_volume',
    'price_change_percentage_24h',
    'market_cap_rank',
    'high_24h',
    'low_24h',
    'last_updated'
]

crypto_data = df_raw[columns_to_keep].copy()

crypto_data.columns = [
    'coin_id',
    'symbol',
    'name',
    'price_inr',
    'market_cap',
    'volume_24h',
    'change_24h_pct',
    'rank',
    'high_24h',
    'low_24h',
    'last_updated'
]


crypto_data

,coin_id,symbol,name,price_inr,market_cap,volume_24h,change_24h_pct,rank,high_24h,low_24h,last_updated
0,bitcoin,btc,Bitcoin,7.632111e+06,152799382297656,1.682722e+12,0.65325,1,7.650670e+06,7.578108e+06,2026-05-10T12:14:11.914Z
1,ethereum,eth,Ethereum,2.192540e+05,26458277417236,9.405059e+11,0.31283,2,2.206490e+05,2.174370e+05,2026-05-10T12:14:13.990Z
2,tether,usdt,Tether,9.441000e+01,17908585103602,3.346774e+12,-0.00299,3,9.448000e+01,9.440000e+01,2026-05-10T12:14:12.167Z
3,ripple,xrp,XRP,1.342600e+02,8295331048439,9.678834e+10,0.05379,4,1.349200e+02,1.333500e+02,2026-05-10T12:14:12.179Z
4,binancecoin,bnb,BNB,6.127000e+04,8259531941446,6.084344e+10,-0.16605,5,6.154900e+04,6.091100e+04,2026-05-10T12:14:11.665Z
5,usd-coin,usdc,USDC,9.441000e+01,7353678549427,5.831794e+11,-0.00096,6,9.484000e+01,9.439000e+01,2026-05-10T12:14:12.489Z
6,solana,sol,Solana,8.820400e+03,5094661407085,2.215391e+11,-0.14006,7,8.929590e+03,8.740930e+03,2026-05-10T12:14:12.733Z
7,tron,trx,TRON,3.305000e+01,3135131219346,3.896234e+10,-0.83621,8,3.335000e+01,3.293000e+01,2026-05-10T12:14:15.121Z
8,figure-heloc,figr_heloc,Figure Heloc,9.715000e+01,1707140921804,1.246039e+10,0.07280,9,9.716000e+01,9.698000e+01,2026-05-10T06:33:46.084Z
9,dogecoin,doge,Dogecoin,1.019000e+01,1572207184561,5.608368e+10,-1.40202,10,1.038000e+01,1.019000e+01,2026-05-10T12:14:18.599Z
10,whitebit,wbt,WhiteBIT Coin,5.625580e+03,1200981270223,4.705889e+09,0.50738,11,5.641960e+03,5.586130e+03,2026-05-10T12:14:02.630Z
11,usds,usds,USDS,9.439000e+01,1054232453460,2.051397e+09,-0.01157,12,9.443000e+01,9.439000e+01,2026-05-10T12:14:03.997Z
12,hyperliquid,hype,Hyperliquid,4.034000e+03,962038111262,1.564996e+10,-2.69977,13,4.145930e+03,4.012710e+03,2026-05-10T12:14:11.275Z
13,cardano,ada,Cardano,2.571000e+01,951234154901,2.514958e+10,-0.54147,14,2.585000e+01,2.538000e+01,2026-05-10T12:14:14.478Z
14,zcash,zec,Zcash,5.709100e+04,950826032414,7.648169e+10,0.39270,15,5.817400e+04,5.547900e+04,2026-05-10T12:14:04.308Z
15,leo-token,leo,LEO Token,9.639400e+02,887411649922,4.887334e+07,-1.04704,16,9.793400e+02,9.638900e+02,2026-05-10T12:14:06.209Z
16,bitcoin-cash,bch,Bitcoin Cash,4.276500e+04,857515131896,1.186952e+10,0.63947,17,4.293000e+04,4.237300e+04,2026-05-10T12:14:18.234Z
17,chainlink,link,Chainlink,9.874100e+02,718021749492,2.090042e+10,-0.10218,18,9.952700e+02,9.717900e+02,2026-05-10T12:14:06.582Z
18,monero,xmr,Monero,3.823300e+04,705625898423,1.057656e+10,-0.34160,19,3.911300e+04,3.788600e+04,2026-05-10T12:14:05.666Z
19,the-open-network,ton,Toncoin,2.278100e+02,606549202782,4.925618e+10,-4.01750,20,2.448300e+02,2.254700e+02,2026-05-10T12:14:02.566Z
20,canton-network,cc,Canton,1.440000e+01,554449807056,7.063347e+08,-4.26646,21,1.513000e+01,1.434000e+01,2026-05-10T12:14:05.887Z
21,stellar,xlm,Stellar,1.540000e+01,515377954572,8.644870e+09,-0.51722,22,1.548000e+01,1.522000e+01,2026-05-10T12:14:06.118Z
22,sui,sui,Sui,1.070700e+02,430002883875,7.065452e+10,7.53576,23,1.085000e+02,9.887000e+01,2026-05-10T12:14:04.058Z
23,litecoin,ltc,Litecoin,5.509350e+03,425255916324,2.338615e+10,0.19581,24,5.538070e+03,5.447000e+03,2026-05-10T12:14:14.925Z
24,memecore,m,MemeCore,3.209300e+02,416881989828,1.044018e+09,0.32480,25,3.295400e+02,3.170200e+02,2026-05-10T12:14:04.739Z
25,dai,dai,Dai,9.439000e+01,416816733135,7.637430e+09,0.00178,26,9.445000e+01,9.435000e+01,2026-05-10T12:14:06.679Z
26,usd1-wlfi,usd1,USD1,9.435000e+01,415944485200,4.655375e+10,-0.03985,27,9.445000e+01,9.432000e+01,2026-05-10T12:14:07.427Z
27,avalanche-2,avax,Avalanche,9.406500e+02,406204576699,1.798597e+10,0.29820,28,9.488900e+02,9.268400e+02,2026-05-10T12:14:12.720Z
28,hedera-hashgraph,hbar,Hedera,9.000000e+00,389904221347,4.460089e+09,2.85850,29,8.990000e+00,8.670000e+00,2026-05-10T12:14:03.668Z
29,ethena-usde,usde,Ethena USDe,9.439000e+01,374270570854,8.162947e+09,0.03827,30,9.441000e+01,9.434000e+01,2026-05-10T12:14:03.464Z
30,shiba-inu,shib,Shiba Inu,6.097400e-04,359128169800,9.432463e+09,0.72082,31,6.102300e-04,5.968400e-04,2026-05-10T12:14:01.823Z
31,rain,rain,Rain,7.148120e-01,341997168465,2.354379e+09,1.11155,32,7.178860e-01,6.952300e-01,2026-05-10T12:14:05.641Z
32,paypal-usd,pyusd,PayPal USD,9.440000e+01,323012145724,2.010628e+09,-0.00958,33,9.443000e+01,9.438000e+01,2026-05-10T12:14:03.015Z
33,crypto-com-chain,cro,Cronos,6.790000e+00,296081758334,1.087803e+09,1.10639,34,6.810000e+00,6.650000e+00,2026-05-10T12:14:06.266Z
34,bittensor,tao,Bittensor,2.959200e+04,284158812707,1.396428e+10,1.30715,35,2.979300e+04,2.887400e+04,2026-05-10T12:14:02.701Z
35,hashnote-usyc,usyc,Circle USYC,1.064900e+02,284182563100,1.064860e+07,NaN,36,NaN,NaN,2026-04-30T15:46:49.733Z
36,tether-gold,xaut,Tether Gold,4.450890e+05,263660397688,7.024230e+09,0.30376,37,4.450710e+05,4.436880e+05,2026-05-10T12:14:02.677Z
37,global-dollar,usdg,Global Dollar,9.442000e+01,261587545754,2.757450e+09,-0.00516,38,9.445000e+01,9.439000e+01,2026-05-10T12:14:04.334Z
38,uniswap,uni,Uniswap,3.714800e+02,234764063311,3.794121e+10,7.43135,39,3.822400e+02,3.421600e+02,2026-05-10T12:14:02.151Z
39,blackrock-usd-institutional-digital-liquidity-...,buidl,BlackRock USD Institutional Digital Liquidity ...,9.443000e+01,230720506705,NaN,0.00000,40,9.443000e+01,9.443000e+01,2026-05-10T11:45:11.419Z
40,polkadot,dot,Polkadot,1.277900e+02,215110885510,1.114351e+10,-0.28518,41,1.283100e+02,1.256900e+02,2026-05-10T12:14:01.713Z
41,mantle,mnt,Mantle,6.460000e+01,213294787189,3.172566e+09,-0.55816,42,6.531000e+01,6.421000e+01,2026-05-10T12:14:08.724Z
42,pax-gold,paxg,PAX Gold,4.453250e+05,210163839569,4.158029e+09,0.25173,43,4.453180e+05,4.440700e+05,2026-05-10T12:14:06.409Z
43,world-liberty-financial,wlfi,World Liberty Financial,6.380000e+00,202803768449,8.846476e+09,-7.51963,44,6.900000e+00,6.360000e+00,2026-05-10T12:14:04.262Z
44,near,near,NEAR Protocol,1.477000e+02,191233775840,1.283272e+10,-1.39317,45,1.497900e+02,1.461000e+02,2026-05-10T12:14:01.541Z
45,ondo-finance,ondo,Ondo,3.918000e+01,189987956039,2.325349e+10,-2.98463,46,4.082000e+01,3.802000e+01,2026-05-10T12:14:02.850Z
46,internet-computer,icp,Internet Computer,3.220800e+02,178206743589,9.679474e+09,-7.33381,47,3.475700e+02,3.223400e+02,2026-05-10T12:14:17.899Z
47,okb,okb,OKB,8.340570e+03,175184918944,1.553485e+09,0.45224,48,8.403020e+03,8.241990e+03,2026-05-10T12:14:04.019Z
48,sky,sky,Sky,7.440000e+00,172503853561,9.942960e+08,-3.21936,49,7.690000e+00,7.430000e+00,2026-05-10T12:14:04.919Z
49,pi-network,pi,Pi Network,1.641000e+01,171322870465,1.013663e+09,0.13009,50,1.653000e+01,1.631000e+01,2026-05-10T12:14:04.580Z

In [ ]:
df = crypto_data.copy()

def categories_market_cap(market_cap):
  if market_cap >= 10_000_000_000_000:
    return "Mega Cap"
  elif market_cap >= 1_000_000_000_000:     # 1-10 Trillion
        return "Large Cap"
  elif market_cap >= 100_000_000_000:       # 100B - 1T
       return "Mid Cap"
  else:
        return "Small Cap"

market_cap_categories = []

for i in range(len(df)):
  market_cap = df.loc[i, 'market_cap']
  category = categories_market_cap(market_cap)
  market_cap_categories.append(category)

df['market_cap_category'] = market_cap_categories

print("\n1. Market Cap Categories Added:")
print(df['market_cap_category'].value_counts())

df

1. Market Cap Categories Added:
market_cap_category
Mid Cap      38
Large Cap     9
Mega Cap      3
Name: count, dtype: int64

,coin_id,symbol,name,price_inr,market_cap,volume_24h,change_24h_pct,rank,high_24h,low_24h,last_updated,market_cap_category
0,bitcoin,btc,Bitcoin,7.632111e+06,152799382297656,1.682722e+12,0.65325,1,7.650670e+06,7.578108e+06,2026-05-10T12:14:11.914Z,Mega Cap
1,ethereum,eth,Ethereum,2.192540e+05,26458277417236,9.405059e+11,0.31283,2,2.206490e+05,2.174370e+05,2026-05-10T12:14:13.990Z,Mega Cap
2,tether,usdt,Tether,9.441000e+01,17908585103602,3.346774e+12,-0.00299,3,9.448000e+01,9.440000e+01,2026-05-10T12:14:12.167Z,Mega Cap
3,ripple,xrp,XRP,1.342600e+02,8295331048439,9.678834e+10,0.05379,4,1.349200e+02,1.333500e+02,2026-05-10T12:14:12.179Z,Large Cap
4,binancecoin,bnb,BNB,6.127000e+04,8259531941446,6.084344e+10,-0.16605,5,6.154900e+04,6.091100e+04,2026-05-10T12:14:11.665Z,Large Cap
5,usd-coin,usdc,USDC,9.441000e+01,7353678549427,5.831794e+11,-0.00096,6,9.484000e+01,9.439000e+01,2026-05-10T12:14:12.489Z,Large Cap
6,solana,sol,Solana,8.820400e+03,5094661407085,2.215391e+11,-0.14006,7,8.929590e+03,8.740930e+03,2026-05-10T12:14:12.733Z,Large Cap
7,tron,trx,TRON,3.305000e+01,3135131219346,3.896234e+10,-0.83621,8,3.335000e+01,3.293000e+01,2026-05-10T12:14:15.121Z,Large Cap
8,figure-heloc,figr_heloc,Figure Heloc,9.715000e+01,1707140921804,1.246039e+10,0.07280,9,9.716000e+01,9.698000e+01,2026-05-10T06:33:46.084Z,Large Cap
9,dogecoin,doge,Dogecoin,1.019000e+01,1572207184561,5.608368e+10,-1.40202,10,1.038000e+01,1.019000e+01,2026-05-10T12:14:18.599Z,Large Cap
10,whitebit,wbt,WhiteBIT Coin,5.625580e+03,1200981270223,4.705889e+09,0.50738,11,5.641960e+03,5.586130e+03,2026-05-10T12:14:02.630Z,Large Cap
11,usds,usds,USDS,9.439000e+01,1054232453460,2.051397e+09,-0.01157,12,9.443000e+01,9.439000e+01,2026-05-10T12:14:03.997Z,Large Cap
12,hyperliquid,hype,Hyperliquid,4.034000e+03,962038111262,1.564996e+10,-2.69977,13,4.145930e+03,4.012710e+03,2026-05-10T12:14:11.275Z,Mid Cap
13,cardano,ada,Cardano,2.571000e+01,951234154901,2.514958e+10,-0.54147,14,2.585000e+01,2.538000e+01,2026-05-10T12:14:14.478Z,Mid Cap
14,zcash,zec,Zcash,5.709100e+04,950826032414,7.648169e+10,0.39270,15,5.817400e+04,5.547900e+04,2026-05-10T12:14:04.308Z,Mid Cap
15,leo-token,leo,LEO Token,9.639400e+02,887411649922,4.887334e+07,-1.04704,16,9.793400e+02,9.638900e+02,2026-05-10T12:14:06.209Z,Mid Cap
16,bitcoin-cash,bch,Bitcoin Cash,4.276500e+04,857515131896,1.186952e+10,0.63947,17,4.293000e+04,4.237300e+04,2026-05-10T12:14:18.234Z,Mid Cap
17,chainlink,link,Chainlink,9.874100e+02,718021749492,2.090042e+10,-0.10218,18,9.952700e+02,9.717900e+02,2026-05-10T12:14:06.582Z,Mid Cap
18,monero,xmr,Monero,3.823300e+04,705625898423,1.057656e+10,-0.34160,19,3.911300e+04,3.788600e+04,2026-05-10T12:14:05.666Z,Mid Cap
19,the-open-network,ton,Toncoin,2.278100e+02,606549202782,4.925618e+10,-4.01750,20,2.448300e+02,2.254700e+02,2026-05-10T12:14:02.566Z,Mid Cap
20,canton-network,cc,Canton,1.440000e+01,554449807056,7.063347e+08,-4.26646,21,1.513000e+01,1.434000e+01,2026-05-10T12:14:05.887Z,Mid Cap
21,stellar,xlm,Stellar,1.540000e+01,515377954572,8.644870e+09,-0.51722,22,1.548000e+01,1.522000e+01,2026-05-10T12:14:06.118Z,Mid Cap
22,sui,sui,Sui,1.070700e+02,430002883875,7.065452e+10,7.53576,23,1.085000e+02,9.887000e+01,2026-05-10T12:14:04.058Z,Mid Cap
23,litecoin,ltc,Litecoin,5.509350e+03,425255916324,2.338615e+10,0.19581,24,5.538070e+03,5.447000e+03,2026-05-10T12:14:14.925Z,Mid Cap
24,memecore,m,MemeCore,3.209300e+02,416881989828,1.044018e+09,0.32480,25,3.295400e+02,3.170200e+02,2026-05-10T12:14:04.739Z,Mid Cap
25,dai,dai,Dai,9.439000e+01,416816733135,7.637430e+09,0.00178,26,9.445000e+01,9.435000e+01,2026-05-10T12:14:06.679Z,Mid Cap
26,usd1-wlfi,usd1,USD1,9.435000e+01,415944485200,4.655375e+10,-0.03985,27,9.445000e+01,9.432000e+01,2026-05-10T12:14:07.427Z,Mid Cap
27,avalanche-2,avax,Avalanche,9.406500e+02,406204576699,1.798597e+10,0.29820,28,9.488900e+02,9.268400e+02,2026-05-10T12:14:12.720Z,Mid Cap
28,hedera-hashgraph,hbar,Hedera,9.000000e+00,389904221347,4.460089e+09,2.85850,29,8.990000e+00,8.670000e+00,2026-05-10T12:14:03.668Z,Mid Cap
29,ethena-usde,usde,Ethena USDe,9.439000e+01,374270570854,8.162947e+09,0.03827,30,9.441000e+01,9.434000e+01,2026-05-10T12:14:03.464Z,Mid Cap
30,shiba-inu,shib,Shiba Inu,6.097400e-04,359128169800,9.432463e+09,0.72082,31,6.102300e-04,5.968400e-04,2026-05-10T12:14:01.823Z,Mid Cap
31,rain,rain,Rain,7.148120e-01,341997168465,2.354379e+09,1.11155,32,7.178860e-01,6.952300e-01,2026-05-10T12:14:05.641Z,Mid Cap
32,paypal-usd,pyusd,PayPal USD,9.440000e+01,323012145724,2.010628e+09,-0.00958,33,9.443000e+01,9.438000e+01,2026-05-10T12:14:03.015Z,Mid Cap
33,crypto-com-chain,cro,Cronos,6.790000e+00,296081758334,1.087803e+09,1.10639,34,6.810000e+00,6.650000e+00,2026-05-10T12:14:06.266Z,Mid Cap
34,bittensor,tao,Bittensor,2.959200e+04,284158812707,1.396428e+10,1.30715,35,2.979300e+04,2.887400e+04,2026-05-10T12:14:02.701Z,Mid Cap
35,hashnote-usyc,usyc,Circle USYC,1.064900e+02,284182563100,1.064860e+07,NaN,36,NaN,NaN,2026-04-30T15:46:49.733Z,Mid Cap
36,tether-gold,xaut,Tether Gold,4.450890e+05,263660397688,7.024230e+09,0.30376,37,4.450710e+05,4.436880e+05,2026-05-10T12:14:02.677Z,Mid Cap
37,global-dollar,usdg,Global Dollar,9.442000e+01,261587545754,2.757450e+09,-0.00516,38,9.445000e+01,9.439000e+01,2026-05-10T12:14:04.334Z,Mid Cap
38,uniswap,uni,Uniswap,3.714800e+02,234764063311,3.794121e+10,7.43135,39,3.822400e+02,3.421600e+02,2026-05-10T12:14:02.151Z,Mid Cap
39,blackrock-usd-institutional-digital-liquidity-...,buidl,BlackRock USD Institutional Digital Liquidity ...,9.443000e+01,230720506705,NaN,0.00000,40,9.443000e+01,9.443000e+01,2026-05-10T11:45:11.419Z,Mid Cap
40,polkadot,dot,Polkadot,1.277900e+02,215110885510,1.114351e+10,-0.28518,41,1.283100e+02,1.256900e+02,2026-05-10T12:14:01.713Z,Mid Cap
41,mantle,mnt,Mantle,6.460000e+01,213294787189,3.172566e+09,-0.55816,42,6.531000e+01,6.421000e+01,2026-05-10T12:14:08.724Z,Mid Cap
42,pax-gold,paxg,PAX Gold,4.453250e+05,210163839569,4.158029e+09,0.25173,43,4.453180e+05,4.440700e+05,2026-05-10T12:14:06.409Z,Mid Cap
43,world-liberty-financial,wlfi,World Liberty Financial,6.380000e+00,202803768449,8.846476e+09,-7.51963,44,6.900000e+00,6.360000e+00,2026-05-10T12:14:04.262Z,Mid Cap
44,near,near,NEAR Protocol,1.477000e+02,191233775840,1.283272e+10,-1.39317,45,1.497900e+02,1.461000e+02,2026-05-10T12:14:01.541Z,Mid Cap
45,ondo-finance,ondo,Ondo,3.918000e+01,189987956039,2.325349e+10,-2.98463,46,4.082000e+01,3.802000e+01,2026-05-10T12:14:02.850Z,Mid Cap
46,internet-computer,icp,Internet Computer,3.220800e+02,178206743589,9.679474e+09,-7.33381,47,3.475700e+02,3.223400e+02,2026-05-10T12:14:17.899Z,Mid Cap
47,okb,okb,OKB,8.340570e+03,175184918944,1.553485e+09,0.45224,48,8.403020e+03,8.241990e+03,2026-05-10T12:14:04.019Z,Mid Cap
48,sky,sky,Sky,7.440000e+00,172503853561,9.942960e+08,-3.21936,49,7.690000e+00,7.430000e+00,2026-05-10T12:14:04.919Z,Mid Cap
49,pi-network,pi,Pi Network,1.641000e+01,171322870465,1.013663e+09,0.13009,50,1.653000e+01,1.631000e+01,2026-05-10T12:14:04.580Z,Mid Cap

In [ ]:
import pandas as pd
import numpy as np
import requests
import json
import random

from datetime import datetime, timedelta

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print("Libraries loaded successfully!")
print(f"Pandas version: {pd.__version__}")

Libraries loaded successfully!
Pandas version: 2.2.2

In [ ]:
np.random.seed(42)

random.seed(42)

num_transactions = 200
start_date = datetime(2026, 1, 1)

transaction_ids = []

for i in range(1001, 1001 + num_transactions):
    txn_id = "QP" + str(i).zfill(6)
    transaction_ids.append(txn_id)

print(f"Generated {len(transaction_ids)} transaction IDs")
print(f"First 5: {transaction_ids[:5]}")
print(f"Last 5: {transaction_ids[-5:]}")

Generated 200 transaction IDs
First 5: ['QP001001', 'QP001002', 'QP001003', 'QP001004', 'QP001005']
Last 5: ['QP001196', 'QP001197', 'QP001198', 'QP001199', 'QP001200']

In [ ]:
amounts = []

for _ in range(num_transactions):
  rand = random.random()

  if rand < 0.3:
    amounts.append(random.randint(100,500))

  elif rand < 0.7:
    amounts.append(random.randint(500, 2000))

  elif rand < 0.95 :
    amounts.append(random.randint(2000, 10000))

  else :
    amounts.append(random.randint(10000,50000))


print(f"Generated {len(amounts)} amounts")
print(f"Sample Amounts : {amounts[:10]}")
print(f"Minimum Rs {min(amounts)}, Maximum amount {max(amounts)\
                                                   } Average : {sum(amounts)//len(amounts)}")

Generated 200 amounts
Sample Amounts : [551, 4006, 477, 479, 2712, 565, 211, 408, 201, 7745]
Minimum Rs 116, Maximum amount 46422 Average : 3546

In [ ]:
dates = []

for _ in range(num_transactions):
    random_days = random.randint(0, 29)
    random_hours = random.randint(8, 22)
    random_minutes = random.randint(0, 59)

    date = start_date + timedelta(days=random_days, hours=random_hours, minutes=random_minutes)
    dates.append(date)

print(f"Generated {len(dates)} dates")
print(f"First date: {dates[0]}")
print(f"Sample dates: {dates[:3]}")

Generated 200 dates
First date: 2026-01-24 20:15:00
Sample dates: [datetime.datetime(2026, 1, 24, 20, 15), datetime.datetime(2026, 1, 9, 10, 50), datetime.datetime(2026, 1, 23, 9, 24)]

In [ ]:

payment_methods = np.random.choice(
    ['UPI', 'Card', 'NetBanking', 'Wallet'],
    size=num_transactions,
    p=[0.55, 0.25, 0.12, 0.08]
)

print(f"Payment method distribution:")
unique, counts = np.unique(payment_methods, return_counts=True)


for method, count in zip(unique, counts):
    print(f"  {method}: {count} ({count/num_transactions*100:.1f}%)")

Payment method distribution:
  Card: 42 (21.0%)
  NetBanking: 27 (13.5%)
  UPI: 116 (58.0%)
  Wallet: 15 (7.5%)

In [ ]:

merchant_categories = np.random.choice(
    ['Electronics', 'Fashion', 'Food & Grocery', 'Travel', 'Entertainment'],
    size=num_transactions,
    p=[0.25, 0.30, 0.25, 0.12, 0.08]
)

regions = np.random.choice(
    ['North', 'South', 'East', 'West', 'Central'],
    size=num_transactions,
    p=[0.25, 0.30, 0.20, 0.15, 0.10]
)

print(f"Generated {len(merchant_categories)} merchant categories")
print(f"Generated {len(regions)} regions")

Generated 200 merchant categories
Generated 200 regions

In [ ]:

statuses = ['SUCCESS'] * num_transactions

print(f"All {len(statuses)} transactions marked as SUCCESS in ledger")

All 200 transactions marked as SUCCESS in ledger

In [ ]:
internal_ledger = pd.DataFrame({
    'transaction_id':transaction_ids,
    'ledger_date':dates,
    'ledger_amount':amounts,
    'payment_method':payment_methods,
    'merchant_category':merchant_categories,
    'region':regions,
    'ledger_status':statuses
})

internal_ledger = internal_ledger.sort_values('ledger_date').reset_index(drop=True)

print(f"Internal Ledger: {len(internal_ledger)} transactions")
print(f"Date range: {internal_ledger['ledger_date'].min()} to {internal_ledger['ledger_date'].max()}")
print(f"Total value: ₹{internal_ledger['ledger_amount'].sum():,}")
print()

Internal Ledger: 200 transactions
Date range: 2026-01-01 08:15:00 to 2026-01-30 20:34:00
Total value: ₹709,343